modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="toraracreatures" #mandatory
version="1.0" #mandatory
displayName="Torara Creatures" #mandatory
logoFile="examplemod.png" #optional
credits="RenatiuX" #optional
authors="BirdHelp" #optional
description='''

        Torara creatures is a mod about adding a wide variety of animals, biomes, and other functions to your world.'''

[[dependencies.toraracreatures]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.toraracreatures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
